spring.application.name=inventoryapi


spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:H:/Ecotokari Ecom/database/dev
#spring.datasource.url=jdbc:h2:mem:testdb

## H2 Deps ##
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/db
spring.h2.console.enabled=true


## Auto Update the Database Sync Tables
spring.jpa.hibernate.ddl-auto=update